# Generated by Django 3.2.8 on 2021-10-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('account', models.CharField(max_length=50)),
                ('ifsc', models.CharField(max_length=50)),
            ],
        ),
    ]
